version: '2'
# networks:
#   hoover_default:
#     external: true
networks:
  default:
    external:
      name: hoover_default
services:
  newsleak-postgres:
    image: "postgres:9.6"
#    ports:
#     - "15432:5432"
    volumes:
     - ./volumes/pg/data:/var/lib/postgresql/data
    env_file:
     - postgres.env
#    networks:
#     - hoover_default
  newsleak-elasticsearch:
    image: "elasticsearch:2.4.6"
    volumes:
     - ./volumes/es/data:/usr/share/elasticsearch/data
#    networks:
#     - hoover_default
#    ports:
#     - "19200:9200"
#     - "19300:9300"
  newsleak-ner:
    image: "uhhlt/newsleak-ner:v0.1"
#    ports:
#      - "5001:5001"
  newsleak-ui:
    image: "uhhlt/newsleak-frontend:v0.1"
    volumes:
     - ./volumes/ui:/etc/settings/
    ports:
     - "9000:9000"
    tty: true
#    networks:
#     - hoover_default
    depends_on:
     - newsleak-postgres
     - newsleak-elasticsearch
     - newsleak-ner
