version: '2'
networks:
  default:
    external:
      name: hoover_default
services:
  newsleak-postgres:
    image: "postgres:9.6"
    volumes:
     - ./volumes/pg/data:/var/lib/postgresql/data
    env_file:
     - postgres.env
  newsleak-elasticsearch:
    image: "elasticsearch:2.4.6"
    volumes:
     - ./volumes/es/data:/usr/share/elasticsearch/data
  newsleak-ner:
    image: "uhhlt/newsleak-ner:v1.0"
  vector-indexing:
    image: "ltphillip/vector-indexing:v0.93"
  newsleak-ui:
    image: "ltphillip/newsleak:v2.5-test-3"
    volumes:
     - ./volumes/ui:/etc/settings/
    ports:
     - "9000:9000"
    tty: true
    container_name: newsleak
    depends_on:
     - newsleak-postgres
     - newsleak-elasticsearch
     - newsleak-ner
     - vector-indexing
